### ISSUE TITLE
Add label filtering capability

### ISSUE THREAD

**Issue by mikesir87** [mikesir87/docker-socket-proxy#4]
As of right now, the proxy only modifies and gates requests and does nothing with filtering the responses.

Add a filter that displays only items with a provided label set. For example:

```yaml
responseFilters:
  - type: requireLabel
    labels:
      com.example.key: value
```

This configuration will filter all requests for containers, images, networks, and volumes to return only the items that have the provided label. When combined with the `addLabel` mutator, this will allow a socket proxy to only see and interact with the items it has created. 😄
